name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "v0.52.0"
      - name: Render Terraform Docs and update README
        uses: terraform-docs/gh-actions@v0.16.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.63.0
          trivy --version
      - name: Cache pre-commit hooks
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  validate-examples:
    name: Validate examples
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: examples
    steps:
      - uses: hashicorp/setup-terraform@v3
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check examples
        env:
          EXAMPLES: simple
        run: |
          for EXAMPLE in ${EXAMPLES}
          do
            echo "Validating $EXAMPLE"...
            cd $EXAMPLE && terraform init && terraform validate && cd -
          done
